### ISSUE TITLE
URL flashes for a given range

### ISSUE THREAD

**Issue by alejandroandreu** [pgr0ss/vim-github-url#4]
Using the plugin works fine when doing so for a specific line, but I found that when selecting a range the URL will quickly display and then disappear before my eyes. Is there any way I can debug this further?

**Comment by pgr0ss** [comment]
I haven't seen this behavior myself. Can you post the output of `vim --version`?

In the past, we've seen similar things when plugins clash with each other. I think the first thing you can do to debug is remove all plugins but this one and see if the problem goes away. If it does, then try to figure out which plugin is clashing. If not, then maybe I can try to reproduce with your specific version of vim.

**Comment by alejandroandreu** [comment]
I recently switched to `nvim` and the behavior is not taking place anymore. I'm closing the issue.
